version: '3.8'

services:
  deno-service:
    build:
      context: ./deno-service
    ports:
      - '8000:8000'
    environment:
      - PORT=8000

  node-service:
    build:
      context: ./node-service
    ports:
      - '8001:8001'
    environment:
      - PORT=8001

  nest-service:
    build:
      context: ./nest-service
    ports:
      - '8002:8002'
    environment:
      - PORT=8002

  monitor-ui:
    build:
      context: ./monitor-ui
    ports:
      - '3000:80'
    depends_on:
      - deno-service
      - node-service
      - nest-service
